feat: include systemd service file in repo
saltstack-formulas/nomad-formula pull request #5
Opened 2019-06-16 01:53 UTC by rbjorklin

Include systemd service file in repo to allow templating.

2019-06-20 10:58 UTC, vutny commented on nomad/defaults.yaml
> +  config_dir: '/etc/nomad.d'
I think you'd need to update the `pillar.example` file as well.

2019-06-24 07:47 UTC, vutny requested changes
I haven't used this formula and Nomad in particular, but the changes look good to me.
One last thing we need to address is fixing paths in `test_nomad_config.py` for CI to pass successfully.

2019-06-28 04:23 UTC, rbjorklin commented
It seems Travis fails to verify that the service is in fact running. Any pointers on how to read the output from `systemd status nomad` within the tests would be appreciated.

2019-07-05 09:58 UTC, vutny commented on pillar.example
> +        {% endfor %}
@rbjorklin I think this addition is preventing Nomad agent to start.

The function must be allowed to call from Salt "mine" explicitly, but the tests seems do not do that.
So, when there are nothing rendered within the for loop, the `retry_join` value would be `None`, which is invalid I suppose.
I suggest you to check if there any values come out from the `mine.get` call first, and only then iterate over them to render complete `server_join` dictionary.

2024-06-14 01:02 UTC, rbjorklin commented
Long abandoned. You should be using Kubernetes.

2024-06-14 01:02 UTC, closed without merging